import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/*

Layout.tsx
---

What is layout.tsx?
- This file defines the template/frame of your website.

Does it make a difference if I dont have a layout.tsx?
- It is not optional. You need to have it.

Important: What is children?
- This is a slot where your actual page content goes.

Important: What is metadata?
- 

What I change in layout.tsx, does that come back in the website?
- Yes. If you add: <body className="bg-black text-white">
- It will come in the website.

*/

// Just some fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// SEO (Search Engine Optimization):
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// This is important (Children):
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
